### ISSUE TITLE
message.message_changed not supported

### ISSUE THREAD

**Issue by joemcmahon** [joemcmahon/mrspiral-spudbot#1]
To repro:
 - Send @spud a message he doesn't understand
 - He may or may not respond
 - try editing the message
 - no response

In the log, there's a message saying something like "slapp:info [evt] tm=T218LB17V ch=C219XNZ52 usr=undefined message.message_changed".

**Comment by spud** [comment]
Please don’t get your spuds confused.

spud, an actual person.

**Comment by joemcmahon** [comment]
👍 thanks!
